stages:
    - build
    - deploy

python:build:
    artifacts:
        paths:
            - dist
        expire_in: 3 days
    cache: &python-cache
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - ".venv"
    image: gitlab.lrz.de:5005/i4/software/docker-images/python3.9-poetry
    needs: []
    rules:
        -   changes:
                - "scan_svn/**.py"
                - .gitlab-ci.yml
        -   if: '$CI_COMMIT_BRANCH == "main"'
        -   if: '$CI_COMMIT_BRANCH == "development"'
    script:
        - poetry install --no-dev
        - poetry build
    stage: build

python:deploy:
    cache: *python-cache
    image: gitlab.lrz.de:5005/i4/software/docker-images/python3.9-poetry
    rules:
    -   if: '$CI_COMMIT_TAG'
    script:
        - poetry config repositories.lrz https://gitlab.lrz.de/api/v4/projects/${CI_PROJECT_ID}/packages/pypi
        - poetry publish --repository lrz --username ${REGISTRY_USERNAME} --password ${REGISTRY_PASSWORD}
    stage: deploy
    needs:
        - python:build
